### ISSUE TITLE
Multi-platform image

### ISSUE THREAD

**Issue by joemaller** [ideasonpurpose/docker-wordpress-dev#38]
Might be one-line? How to test?

```yaml
     -  name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/app:latest
```

https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md```
