### ISSUE TITLE
Use anchors in docker-compose files

### ISSUE THREAD

**Issue by joemaller** [ideasonpurpose/docker-wordpress-dev#66]
[YAML spec on Alias Nodes](https://yaml.org/spec/1.2-old/spec.html#id2786196) (`&`anchors and `*`aliases)

 Something like this could work? 

```yaml
services:
  db:
    image: &db_img mariadb:11.0.3

  wp:
    image: &wp_img ideasonpurpose/wordpress:6.3

  other_db_service:
    image: *db_img   // reference returns "mariadb:11.0.3"

  other_wp_service:
    image: *wp_img // reference returns "ideasonpurpose/wordpress:6.3"
```
